const assert = require("assert")
const fs = require("fs")
const path = require("path")
const src = fs.readFileSync(path.join(__dirname, "..", "Model.js"), "utf8")
  .replace(/^\.pragma library\s*/, "")
eval(src)

assert.equal(SURFACES.length, 3)
assert.equal(defaultConfig().surfaces["apple-music"].enabled, true)
assert.equal(defaultConfig().surfaces["youtube"].enabled, false)
assert.equal(mergeConfig({ surfaces: { youtube: { enabled: true, scale: 0.9 } } }).surfaces.youtube.enabled, true)
assert.equal(mergeConfig({ surfaces: { youtube: { scale: 9 } } }).surfaces.youtube.scale, 0.94)
assert.equal(cssPercent(0.92), "92%")
assert.equal(hostToSurfaceId("music.apple.com"), "apple-music")
assert.equal(hostToSurfaceId("www.youtube.com"), "youtube")
assert.equal(hostToSurfaceId("youtu.be"), "youtube")
assert.equal(appleMusicCss("iA Writer Mono S", 0.92).indexOf("92%") !== -1, true)
assert.equal(grokBotCss("iA Writer Mono S", 1).indexOf("--cursor-font-family") !== -1, true)
assert.equal(youtubeCss("iA Writer Mono S", 0.94).indexOf("Roboto") !== -1, true)
assert.equal(cssForSurface("nope", "X", 1), "")
console.log("omarchy-type model tests passed")
